CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  role ENUM('admin', 'be') NOT NULL DEFAULT 'be',
  pin_hash VARCHAR(255) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stores (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  store_code SMALLINT UNSIGNED NOT NULL UNIQUE,
  name VARCHAR(160) NOT NULL UNIQUE,
  segment VARCHAR(40) NOT NULL,
  gold_target DECIMAL(20,0) NOT NULL DEFAULT 0,
  meezan_target DECIMAL(20,0) NOT NULL DEFAULT 0,
  silver_target DECIMAL(20,0) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_brands (
  user_id BIGINT UNSIGNED NOT NULL,
  brand_code ENUM('goldgram', 'meezan_gold', 'silvergram') NOT NULL,
  PRIMARY KEY (user_id, brand_code),
  CONSTRAINT fk_php_user_brands_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS realisations (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  store_id BIGINT UNSIGNED NOT NULL,
  year SMALLINT UNSIGNED NOT NULL,
  month_index TINYINT UNSIGNED NOT NULL,
  gold DECIMAL(20,0) NOT NULL DEFAULT 0,
  meezan DECIMAL(20,0) NOT NULL DEFAULT 0,
  silver DECIMAL(20,0) NOT NULL DEFAULT 0,
  note TEXT NULL,
  submitted_by BIGINT UNSIGNED NULL,
  submitted_name VARCHAR(120) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_php_realisations_store_period (store_id, year, month_index),
  CONSTRAINT fk_php_realisations_store FOREIGN KEY (store_id) REFERENCES stores(id),
  CONSTRAINT fk_php_realisations_user FOREIGN KEY (submitted_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NULL,
  action VARCHAR(60) NOT NULL,
  entity VARCHAR(60) NOT NULL,
  entity_id VARCHAR(120) NULL,
  old_value JSON NULL,
  new_value JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_php_audit_user_created (user_id, created_at),
  CONSTRAINT fk_php_audit_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
